version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./documents:/app/documents
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb
    privileged: true

volumes:
  documents: